language: python
python:
  - "2.7"

before_install:
  - sudo apt-get install -qq -y cgroup-lite slirp aufs-tools ca-certificates
  - >
    sudo curl -sLo
    /usr/local/bin/docker
    https://get.docker.io/builds/Linux/x86_64/docker-1.0.0
  - sudo chmod +x /usr/local/bin/docker
  - >
    curl -sLo sekexe.zip
    https://github.com/jpetazzo/sekexe/archive/c5119f039140194f70a7ffa83e039b88960818c7.zip
  - unzip sekexe.zip
  - mv sekexe-* ./sekexe
  - sudo mkdir -p /var/lib/docker
  - sudo mkdir -p /sys/fs/cgroup

install:
  - pip install -r requirements-dev.txt

script:
  - |
    # prepare a little bash script for sekexe
    cat > ./run.sh <<CMD
    #!/bin/bash

    set -e

    # where to keep the docker pid
    PIDFILE=/var/run/docker.pid

    # make sure docker stops at the end
    stop_docker() {
      (
        if [[ -f \$PIDFILE ]]
        then
          kill \$(cat \$PIDFILE)
        fi
      )
    }
    trap stop_docker EXIT

    # remount the cgroups
    cgroups-umount
    cgroups-mount

    # make sure we're in this directory
    cd $(pwd)

    # start docker backgrounded
    docker -d -p \$PIDFILE >/dev/null 2>&1 &

    # wait for docker to be ready
    sleep 5

    # run the tests
    $(which behave)
    CMD

    # make the script executable
    chmod +x ./run.sh

    # run the script with sekexe
    sudo ./sekexe/run "$(pwd)/run.sh"

  - exit $?
